export { default as ForestBro } from "./Forest-bro.svg"
export { default as ForestPana } from "./Forest-pana.svg"
export { default as ForestRafiki } from "./Forest-rafiki.svg"
export { default as HappySunRafiki } from "./Happy Sun-rafiki.svg"
export { default as MangoTreeAmico } from "./Mango tree-amico.svg"
export { default as SpringFlowerCuate } from "./Spring flower-cuate.svg"
export { default as SpringFlowerPana } from "./Spring flower-pana.svg"
export { default as StrelitziaPlantRafiki } from "./strelitzia plant-rafiki.svg"
export { default as SunsetPana } from "./Sunset-pana.svg"
export { default as WindTurbineCuate } from "./Wind turbine-cuate.svg"